# Description:
# This workflow automates the process of building and pushing a Docker image
# The image is tagged with the current GitHub Actions run number for unique identification.

name: docker build and push image 

on:
  workflow_dispatch:
  push:

env:
  OWNER_NAME: 1devops2
  REPOSITORY_NAME: workzone-freelancer-marketplace-for-gig-service-order-job-posting-laravel

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     # tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:latest
      #     tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}

      - name: check if docker-compose is installed
        run: docker-compose up -d