# Description:
# This workflow automates the process of building and pushing a Docker image
# The image is tagged with the current GitHub Actions run number for unique identification.

name: docker build and push image 

on:
  workflow_dispatch:
  push:

env:
  OWNER_NAME: 1devops2
  REPOSITORY_NAME: workzone-freelancer-marketplace-for-gig-service-order-job-posting-laravel
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  docker-build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:latest
          tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}

      - name: docker-compose setup and deploy
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker-compose.yaml"

      - name: Wait for the container to start
        run: |
          echo "Waiting for the container to start..."
          sleep 5 

      - name: Verify the application is accessible
        run: |
          for i in {1..3}; do
            if curl -s --head http://localhost:80 | grep "200 OK"; then
              echo "Application is accessible."
              exit 0
            fi
            echo "Application is not accessible yet. Retrying in 5 seconds..."
            sleep 2
          done
          echo "Application is not accessible after multiple attempts."
          exit 1